"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var book_1 = require("./book");
var library_1 = require("./library");
var book1 = new book_1.Book("Introduccion a Javascript", 233, "2344433-BC23333", "Joseph Smith", "Now Editions");
var book2 = new book_1.Book("Introduccion a Python", 589, "5555555-BC23333", "Che Guevara", "Pythoners");
var book3 = new book_1.Book("Introduccion a Java", 477, "6666666-BC23333", "Mariano Ortiz", "EditorPro");
var book4 = new book_1.Book("Introduccion a Typescript", 666, "7777777-BC23333", "Pepito Fernandez", "CreamEditions");
var library1 = new library_1.Library([book1, book2, book3, book4], "Calle de atras", "Pepito Lopez");
var library2 = new library_1.Library([book1, book3], "Calle del medio", "Paco Puertas");
var library3 = new library_1.Library([book2, book3, book4], "Calle de alante", "Ignacio Ilustre");
console.log(library1.getAddress());
library1.setAddress("Prueba direccion");
console.log(library1.getAddress());
console.log(library1.getManager());
library1.setManager("Prueba manager");
console.log(library1.getManager());
console.log(library1.toString());
console.log(library2.toString());
console.log(library3.toString());
