"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var point_1 = require("./point");
var myPoint = new point_1.Point(4, 6);
var myPoint2 = new point_1.Point(15, 20);
console.log(myPoint.toString());
console.log(myPoint.getX());
myPoint.setX(58);
console.log(myPoint.getX());
console.log(myPoint.toString());
console.log(myPoint.getY());
myPoint.setY(22);
console.log(myPoint.getY());
console.log(myPoint.toString());
console.log(myPoint.distanceToOrigin());
console.log(myPoint.calculateDistance(myPoint2));
