"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var point_1 = require("./point");
var myPoint = new point_1.Point(4, 6);
var myPoint2 = new point_1.Point(15, 20);
var myPoint3 = new point_1.Point(44, 22);
var myPoint4 = new point_1.Point(74, 1);
var myPoint5 = new point_1.Point(12, 10);
console.log(myPoint.toString());
console.log(myPoint.getX());
myPoint.setX(45);
console.log(myPoint.getX());
console.log(myPoint.toString());
console.log(myPoint.getY());
myPoint.setY(22);
console.log(myPoint.getY());
console.log(myPoint.toString());
console.log(myPoint.distanceToOrigin());
console.log(myPoint.calculateDistance(myPoint2));
console.log(myPoint.calcularQuadrant());
console.log(myPoint.calculateNearest([myPoint2, myPoint3, myPoint4, myPoint5]));
